INSERT INTO DB_PAYMENT (ID, AMOUNT, CANCELED, CREDITOR_IBAN, CURRENCY, DEBTOR_IBAN, INSERT_DATE, TYPE) VALUES (1, 100.10,FALSE, 'iban1', 'EUR', 'iban1', TIMESTAMP '2025-06-02 14:34:00', 'TYPE1');
INSERT INTO DB_PAYMENT_TYPE1 (DETAILS, PAYMENT_ID) VALUES ('test1', 1);
INSERT INTO DB_PAYMENT (ID, AMOUNT, CANCELED, CREDITOR_IBAN, CURRENCY, DEBTOR_IBAN, INSERT_DATE, TYPE) VALUES (2, 200, FALSE, 'iban2', 'USD', 'iban2', CURRENT_TIMESTAMP, 'TYPE2');
INSERT INTO DB_PAYMENT_TYPE2 (DETAILS, PAYMENT_ID) VALUES ('test2', 2);
INSERT INTO DB_PAYMENT (ID, AMOUNT, CANCELED, CREDITOR_IBAN, CURRENCY, DEBTOR_IBAN, INSERT_DATE, TYPE) VALUES (3, 300, FALSE, 'iban3', 'EUR', 'iban3', DATEADD('HOUR', -2, CURRENT_TIMESTAMP), 'TYPE3');
INSERT INTO DB_PAYMENT_TYPE3 (CREDITOR_BIC, PAYMENT_ID) VALUES ('test3', 3);
INSERT INTO DB_PAYMENT (ID, AMOUNT, CANCELED, CREDITOR_IBAN, CURRENCY, DEBTOR_IBAN, INSERT_DATE, TYPE) VALUES (4, 444, FALSE, 'iban4', 'USD', 'iban4', CURRENT_TIMESTAMP, 'TYPE3');
INSERT INTO DB_PAYMENT_TYPE3 (CREDITOR_BIC, PAYMENT_ID) VALUES ('test3', 4);
ALTER TABLE db_payment ALTER COLUMN id RESTART WITH 5;